"""version1_patrick_a — window, colors, states (no sidebar)."""

GRID_SIZE = 28
CELL_SIZE = 18

ARENA_WIDTH = GRID_SIZE * CELL_SIZE
ARENA_HEIGHT = GRID_SIZE * CELL_SIZE

SIDEBAR_WIDTH = 0
WINDOW_WIDTH = ARENA_WIDTH
WINDOW_HEIGHT = ARENA_HEIGHT

BASE_FPS = 8

COLOR_BG = (0x1A, 0x1A, 0x2E)
COLOR_GRID = (32, 32, 54)
COLOR_BORDER = (68, 68, 102)
COLOR_SNAKE_HEAD = (0, 220, 100)
COLOR_SNAKE_BODY = (0, 140, 70)

SNAKE_START_LENGTH = 3
SNAKE_START_X = GRID_SIZE // 2
SNAKE_START_Y = GRID_SIZE // 2

STATE_MENU = "MENU"
STATE_PLAYING = "PLAYING"
STATE_GAME_OVER = "GAME_OVER"
