"""
Snake+ — version0 scaffold: all architecture constants (EC327).

Exact values from design brief (plus derived / forward-looking names).
"""

from __future__ import annotations

# --- Grid / window (derived) ---
GRID_SIZE = 28
CELL_SIZE = 18
SIDEBAR_WIDTH = 200

ARENA_WIDTH = GRID_SIZE * CELL_SIZE
ARENA_HEIGHT = GRID_SIZE * CELL_SIZE
WINDOW_WIDTH = ARENA_WIDTH + SIDEBAR_WIDTH
WINDOW_HEIGHT = ARENA_HEIGHT

# --- Timing / difficulty ---
BASE_FPS = 8
MAX_FPS = 20
DIFFICULTY_INCREASE_INTERVAL_S = 30.0
FPS_INCREASE_PER_LEVEL = 1

CHASER_SNAKE_MOVE_EVERY_TICKS = 5
CHASER_HUNT_DURATION_S = 15.0
CHASER_COOLDOWN_S = 10.0
CHASER_MIN_SPAWN_DISTANCE = 8

# --- Health (brief) ---
HP_MAX = 3
PLAYER_MAX_HP = HP_MAX
INVINCIBILITY_DURATION_S = 1.5

# --- Scoring / food (brief names + aliases for later modules) ---
SCORE_NORMAL_FOOD = 20
SCORE_GOLDEN_FOOD = 80
SCORE_FOOD_NORMAL = SCORE_NORMAL_FOOD
SCORE_FOOD_GOLDEN = SCORE_GOLDEN_FOOD
GROW_FOOD_NORMAL = 1
GROW_FOOD_GOLDEN = 3

NORMAL_FOOD_COUNT = 6
GOLDEN_FOOD_MAX = 2
GOLDEN_FOOD_DURATION_S = 6.0
GOLDEN_FOOD_SPAWN_INTERVAL_S = 4.0
GOLDEN_FOOD_SPAWN_CHANCE_PER_CHECK = min(1.0, 0.15 * 1.15)

SCORE_BONUS_CHERRY = 150
SCORE_SURVIVAL_BONUS = 15
SURVIVAL_BONUS_INTERVAL_S = 15.0
SCORE_MULTIPLIER_VALUE = 2
SCORE_MULTIPLIER_DURATION_S = 10.0
SCORE_FLASH_DURATION_S = 0.35

# --- Enemy thresholds ---
SCORE_CHASER_SNAKE_APPEAR = 80
SCORE_BLOCKER_START = 30
CHASER_BASE_LENGTH = 3
CHASER_MAX_LENGTH = 7
BLOCKER_MAX_COUNT = 9
BLOCKER_SPAWN_INTERVAL_S = 21.0
BLOCKER_RESPAWN_AFTER_REMOVE_S = 5.0

# --- Snake start ---
SNAKE_START_LENGTH = 5
SNAKE_START_POS_X = GRID_SIZE // 2
SNAKE_START_POS_Y = GRID_SIZE // 2

# --- Colors (brief + extended theme) ---
COLOR_BG = (26, 26, 46)
COLOR_SNAKE_HEAD = (0, 255, 136)
COLOR_SNAKE_BODY = (0, 85, 51)
COLOR_SNAKE_TAIL = COLOR_SNAKE_BODY
COLOR_SNAKE_OUTLINE = (0, 100, 70)
COLOR_FOOD = (255, 255, 255)
COLOR_FOOD_NORMAL = COLOR_FOOD
COLOR_GOLDEN_FOOD = (255, 215, 0)
COLOR_FOOD_GOLDEN = COLOR_GOLDEN_FOOD
COLOR_ENEMY_CHASER = (255, 107, 53)
COLOR_CHASER_HEAD = COLOR_ENEMY_CHASER
COLOR_CHASER_BODY = (204, 68, 0)
COLOR_CHASER_EYE = (255, 255, 255)
COLOR_BLOCKER = (100, 100, 120)
COLOR_ENEMY_BLOCKER = COLOR_BLOCKER

COLOR_GRID_LINE = (32, 32, 54)
COLOR_BORDER = (68, 68, 102)
COLOR_SIDEBAR_BG = (18, 18, 30)
COLOR_TEXT = (235, 235, 245)
COLOR_TEXT_MUTED = (155, 155, 175)
COLOR_HEART_LOST = (90, 90, 110)
COLOR_SCORE_FLASH = (255, 235, 140)
COLOR_SNAKE_DAMAGE = (255, 60, 60)
COLOR_SHIELD_FLASH = (255, 255, 255)
COLOR_OVERLAY = (0, 0, 0)

COLOR_ITEM_PORTAL = (180, 80, 255)
COLOR_ITEM_HEART = (255, 80, 90)
COLOR_ITEM_STAR = (255, 215, 80)
COLOR_ITEM_MAGNET = (80, 160, 255)
COLOR_ITEM_SHIELD = (90, 220, 140)
COLOR_ITEM_CHERRY = (255, 80, 200)
COLOR_CHASER_HUD_ACTIVE = (255, 70, 70)
COLOR_CHASER_HUD_COOLDOWN = (140, 140, 160)

# --- Items / portals (timing) ---
PORTAL_PAIR_MAX = 1
PORTAL_DURATION_S = 12.0
PORTAL_GLOW_PULSE_SPEED = 3.0
PORTAL_RESPAWN_INTERVAL_S = 45.0
PORTAL_RESPAWN_CHANCE = 0.35

HEART_ITEM_MAX = 1
HEART_MIN_SCORE_FOR_SPAWN = 0
HEART_SPAWN_INTERVAL_S = 5.0
HEART_SPAWN_CHANCE = 0.75
HEART_PULSE_PERIOD_S = 0.8
HEART_PULSE_SCALE_MIN = 1.0
HEART_PULSE_SCALE_MAX = 1.15

MULTIPLIER_ITEM_MAX = 1
STAR_SPAWN_INTERVAL_S = 6.0
STAR_SPAWN_CHANCE = 0.35

MAGNET_ITEM_MAX = 1
MAGNET_DURATION_S = 6.0
MAGNET_RADIUS_CELLS = 4
MAGNET_SPAWN_INTERVAL_S = 12.0
MAGNET_SPAWN_CHANCE_PER_CHECK = 0.25

SHIELD_ITEM_MAX = 1
SHIELD_SPAWN_INTERVAL_S = 12.0
SHIELD_SPAWN_CHANCE_PER_CHECK = 0.25

CHERRY_ITEM_MAX = 1
CHERRY_SPAWN_INTERVAL_S = 5.0
CHERRY_SPAWN_CHANCE = min(1.0, 0.20 + 0.10)
CHERRY_DURATION_S = 4.0

FOOD_RESPAWN_TRY_INTERVAL_S = 0.3
FOOD_FORCE_RESPAWN_THRESHOLD_S = 1.0
GOLDEN_FOOD_PULSE_ALPHA_MIN = 150
GOLDEN_FOOD_PULSE_ALPHA_MAX = 255
GOLDEN_FOOD_PULSE_SPEED = 4.0

GRID_LINE_WIDTH = 1
BORDER_LINE_WIDTH = 3
CELL_INSET = 2
SNAKE_CORNER_RADIUS = 4
ITEM_MIN_DRAW_PX = 14
FOOD_RADIUS = 5
GOLDEN_FOOD_RADIUS = 6
PORTAL_SIZE_INSET = 3

HUD_PADDING = 12
HUD_LINE_GAP = 8
HUD_SCORE_SIZE = 40
HUD_LABEL_SIZE = 18
HUD_SMALL_SIZE = 14
POWERUP_BAR_HEIGHT = 10
POWERUP_BAR_WIDTH = SIDEBAR_WIDTH - HUD_PADDING * 2
CONTROLS_HINT_TOP_PAD = 12

PARTICLES_ON_EAT = 8
PARTICLE_LIFETIME_S = 0.5
PARTICLE_SPEED_PX_PER_S = 180.0
PARTICLE_RADIUS_PX = 2
SHAKE_DISTANCE_PX = 8
SHAKE_DURATION_S = 0.4
SHIELD_FLASH_DURATION_S = 0.25
SHIELD_FLASH_MAX_RADIUS_PX = 180

HIGHSCORE_FILE = "highscore.json"
HIGHSCORE_KEY = "high_score"

STATE_MENU = "MENU"
STATE_PLAYING = "PLAYING"
STATE_PAUSED = "PAUSED"
STATE_GAME_OVER = "GAME_OVER"

PAUSE_KEY = "p"
KEY_START = "return"
KEY_RESTART = "r"
KEY_QUIT = "q"
KEY_PAUSE = "p"
KEY_ACTION = "space"
