"""version1_patrick_b — sidebar + scoring."""

GRID_SIZE = 28
CELL_SIZE = 18

ARENA_WIDTH = GRID_SIZE * CELL_SIZE
ARENA_HEIGHT = GRID_SIZE * CELL_SIZE

SIDEBAR_WIDTH = 200
WINDOW_WIDTH = ARENA_WIDTH + SIDEBAR_WIDTH
WINDOW_HEIGHT = ARENA_HEIGHT

BASE_FPS = 8

HIGHSCORE_FILE = "highscore.json"
HIGHSCORE_KEY = "high_score"

NORMAL_FOOD_COUNT = 3
SCORE_FOOD_NORMAL = 10
GROW_FOOD_NORMAL = 1

FOOD_RESPAWN_TRY_INTERVAL_S = 0.25

COLOR_BG = (0x1A, 0x1A, 0x2E)
COLOR_GRID = (32, 32, 54)
COLOR_BORDER = (68, 68, 102)
COLOR_SNAKE_HEAD = (0, 220, 100)
COLOR_SNAKE_BODY = (0, 140, 70)
COLOR_FOOD = (255, 255, 255)

COLOR_SIDEBAR_BG = (18, 18, 30)
COLOR_TEXT = (235, 235, 245)
COLOR_TEXT_MUTED = (150, 150, 170)

FOOD_RADIUS = 5

SNAKE_START_LENGTH = 3
SNAKE_START_X = GRID_SIZE // 2
SNAKE_START_Y = GRID_SIZE // 2

STATE_MENU = "MENU"
STATE_PLAYING = "PLAYING"
STATE_GAME_OVER = "GAME_OVER"

HUD_PADDING = 14
HUD_LINE_GAP = 8
